from dataclasses import dataclass


@dataclass(frozen=True)
class Evidence:
    """
    Represents the clinical evidence retrieved from the knowledge base
    that supports a response generated by the AI agent.
    """

    document_name: str
    section: str
    chunk_id: str
    score: float

    def __post_init__(self) -> None:
        """
        Ensures the similarity score is between 0.0 and 1.0.
        """
        if not 0.0 <= self.score <= 1.0:
            raise ValueError("score must be between 0.0 and 1.0")