from dataclasses import dataclass


@dataclass(frozen=True)
class LLMResponse:
    """
    Represents the structured response generated by the language model.
    """

    content: str
    evidence_used: tuple[str, ...]